#!/bin/sh

# Xcode Cloud runs this straight after cloning, before it resolves dependencies or
# invokes xcodebuild.
#
# Janitor.xcodeproj and Support/Info.plist are generated by XcodeGen from project.yml
# and are gitignored, so a fresh clone has no project to build. Xcode Cloud fails with:
#
#   Project Janitor.xcodeproj does not exist at the root of the repository
#
# This script installs XcodeGen and regenerates the project and its shared scheme.

set -e

# Homebrew lives at /opt/homebrew on Xcode Cloud's Apple silicon runners.
export PATH="/opt/homebrew/bin:$PATH"
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

echo "▸ Installing XcodeGen…"
brew install xcodegen

# Xcode Cloud invokes ci_scripts from the ci_scripts/ directory. Generate at the
# repository root instead.
cd "${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"

echo "▸ Generating Janitor.xcodeproj from project.yml…"
xcodegen generate

echo "▸ Done — generated:"
ls -d Janitor.xcodeproj Support/Info.plist
