#!/bin/sh

# Xcode Cloud runs this straight after cloning, before it resolves dependencies or
# invokes xcodebuild. It is the only automated caller: the self-hosted CI lane that also
# ran it is commented out (see .github/workflows/ci.yml). Run it by hand to check it still
# works.
#
# Janitor.xcodeproj and Support/Info.plist are generated by XcodeGen from project.yml
# and are gitignored, so a fresh clone has no project to build. Xcode Cloud fails with:
#
#   Project Janitor.xcodeproj does not exist at the root of the repository
#
# This script installs XcodeGen if it is missing, then regenerates the project and its
# shared scheme.

set -e

# Homebrew lives at /opt/homebrew on Xcode Cloud's Apple silicon runners.
export PATH="/opt/homebrew/bin:$PATH"
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

# Xcode Cloud's runner is ephemeral and carries no XcodeGen, so it installs one. A
# development Mac already has it, so it skips a network round trip.
if command -v xcodegen >/dev/null 2>&1; then
	echo "▸ XcodeGen is already installed: $(xcodegen --version 2>&1 | tr -d '\n')"
else
	echo "▸ Installing XcodeGen…"
	brew install xcodegen
fi

# Xcode Cloud invokes ci_scripts from the ci_scripts/ directory. Generate at the
# repository root instead.
cd "${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"

echo "▸ Generating Janitor.xcodeproj from project.yml…"
xcodegen generate

echo "▸ Done — generated:"
ls -d Janitor.xcodeproj Support/Info.plist
