//  Pasteboard.swift
//  Writing to the macOS pasteboard, with a Value marked so the rest of the system
//  leaves it alone.
//
//  A copied Value is plaintext on a surface Janitor does not own. Three markers narrow
//  what happens to it next. None of them is enforced by the operating system.
//
//  - `org.nspasteboard.ConcealedType` means "this is a password, do not record it". It
//    is a convention rather than an API, and the widely used clipboard managers honor
//    it.
//  - `org.nspasteboard.TransientType` means "do not store this at all". Same
//    convention, same standing.
//  - `com.apple.is-sensitive` is what keeps an item off Universal Clipboard, so it does
//    not reach the operator's other devices. Apple does not document it. It is included
//    because it is the only lever there is, and it costs an empty data item.
//
//  A fourth convention, `org.nspasteboard.AutoGeneratedType`, is deliberately absent. It
//  means the application put the content there and the operator did not ask for it.
//  Every copy here is an explicit menu choice, so the marker would be a false statement.
//
//  A clipboard manager that ignores the conventions still records the Value. These are
//  the strongest controls the platform offers, not a guarantee.
//
//  `clearIfOwned` is the fourth control. It clears the pasteboard only while Janitor
//  still owns the contents, so a Value that aged out is removed without wiping
//  something the operator copied in the meantime.

import AppKit

@MainActor
enum Pasteboard {
    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let sensitive = NSPasteboard.PasteboardType("com.apple.is-sensitive")

    /// Every marker a concealed copy carries, in the order they are written.
    static let concealedMarkers = [concealed, transient, sensitive]

    /// The board a copy goes to. The app writes to the system pasteboard. A test points
    /// this at a private board of its own, so running the suite never disturbs whatever
    /// the operator has copied.
    ///
    /// Changing the board drops ownership: a change count is only meaningful against the
    /// board it was read from.
    static var board: NSPasteboard = .general {
        didSet { ownedChangeCount = nil }
    }

    /// The change count of the last Value Janitor wrote, so a later clear can tell
    /// whether the contents are still ours.
    private static var ownedChangeCount: Int?

    /// Copy metadata — an Entry name, an environment, an ARN. Not secret, so it is
    /// written plainly and left for the operator to manage.
    static func copyPlain(_ text: String) {
        board.clearContents()
        board.setString(text, forType: .string)
        ownedChangeCount = nil
    }

    /// Copy a revealed Value, marked concealed, transient, and sensitive.
    static func copyConcealed(_ text: String) {
        board.clearContents()
        board.setString(text, forType: .string)
        // The markers carry no payload. Their presence is the signal.
        for marker in concealedMarkers {
            board.setData(Data(), forType: marker)
        }
        ownedChangeCount = board.changeCount
    }

    /// Clear the pasteboard, but only while it still holds what Janitor put there.
    static func clearIfOwned() {
        guard let owned = ownedChangeCount else { return }
        ownedChangeCount = nil
        guard board.changeCount == owned else { return }
        board.clearContents()
    }
}
